### ISSUE TITLE
Morning session: Peer-to-peer code review B4D4

### ISSUE THREAD

**Issue by MudasirSherwani** [UmerZia/Portfolio#10]
### Hi, @UmerZia :wave: 

 We find that your project is:

1. Followed Gitflow.
2. Good commit messages.
3. Linters are passing.
4. Professional readme.

 **But there is something that needs to work.**
I would like to suggest you please fix the problem on the first card of the project work area , when a user hovers the mouse on the first card it forces all cards to move down.

**Comment by UmerZia** [comment]
Sure I will look over those mentioned issues. 😄
